/**
 * components/ai/AiDisclosure.tsx  (advice-boundary slice)
 *
 * The PERSISTENT disclosure: one quiet line under the composer, in both layouts
 * and at every width, that says what every answer here is — AI-generated insight
 * from the user's own data, not professional financial advice — with an "About"
 * disclosure for the longer explanation.
 *
 * ⚠️ ALWAYS PRESENT, NEVER IN THE WAY. It sits below the input, never over the
 * conversation, and the longer text is behind a native <details> (keyboard and
 * screen-reader operable, no state, no script) so it costs one line until asked.
 * The contextual note beside a consequential answer is a different component
 * (GuidanceNote) driven by the answer's label; this line does not change with it.
 *
 * ⚠️ PRODUCT COPY, NOT COUNSEL-APPROVED LANGUAGE. It states facts about the
 * software (AI-generated, can be wrong, not a licensed professional) and makes
 * no claim about Fourth Meridian's legal classification.
 * See docs/systems/ai-financial-guidance-boundary.md.
 *
 * Presentation only.
 */

export const AI_DISCLOSURE_LINE = "AI-generated insights · Not professional financial advice";

export const AI_DISCLOSURE_ABOUT: readonly string[] = [
  "Answers are generated by AI from the accounts and history connected to this Space.",
  "They can be incomplete or wrong. Check the figures and assumptions before you act on them.",
  "Fourth Meridian AI is not a licensed financial adviser, broker, tax adviser or attorney, and an AI answer shouldn't be the only basis for an important financial decision.",
];

export function AiDisclosure() {
  return (
    <details data-ai-disclosure className="group text-center">
      <summary className="mx-auto inline-flex cursor-pointer list-none items-center gap-1.5 rounded px-1 marker:hidden [&::-webkit-details-marker]:hidden focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-info)]">
        <span>{AI_DISCLOSURE_LINE}</span>
        <span aria-hidden>·</span>
        <span className="underline decoration-dotted underline-offset-2">About</span>
      </summary>
      <div className="mx-auto mt-2 max-w-xl space-y-1 text-left leading-relaxed">
        {AI_DISCLOSURE_ABOUT.map((s) => <p key={s}>{s}</p>)}
      </div>
    </details>
  );
}
