/**
 * lib/password-reset-token.ts
 *
 * D11 (Phase 2 schema modernization) — hash passwordResetToken at rest.
 *
 * Unlike recovery codes (lib/recovery-codes.ts) or passwords, a password
 * reset token is not a low-entropy human-typed secret — it's
 * crypto.randomBytes(32) (256 bits) generated by the server. bcrypt's
 * per-guess slow hashing exists to blunt brute-force guessing of low-entropy
 * input; it buys nothing here and would force an O(n) bcrypt.compare loop
 * over every outstanding token just to look one up. A plain fast hash with
 * an exact-match DB lookup is the right tool: the token's own entropy is the
 * security property, not the hash function's slowness.
 *
 * SHA-256, hex-encoded. Deterministic so `db.user.findFirst({ where: {
 * passwordResetToken: hashResetToken(token) } })` keeps working as a direct
 * equality lookup, same call shape as today, just hashed.
 */

import { createHash } from "crypto";

export function hashResetToken(rawToken: string): string {
  return createHash("sha256").update(rawToken).digest("hex");
}
