/**
 * lib/ai/types.ts
 *
 * Core type contracts for the AI Context Builder (D4).
 *
 * Design principles:
 * - ContextDomain is an open string type, not an enum. This keeps the
 *   contract template-agnostic — finance, travel, business, property, and
 *   future Space types all register their own domain strings without touching
 *   this file.
 * - FinanceDomains provides the canonical constants for the built-in finance
 *   template. Non-finance templates define their own constants elsewhere.
 * - SpaceContext_AI uses an open Record<string, ContextDomainSection> for
 *   domains rather than named fields, for the same reason.
 * - Signals are deterministic and rule-based. No LLM calls here.
 *
 * Security invariant (enforced by lint rule — see eslint config):
 *   No file under lib/ai/ may import lib/plaid/encryption or call any
 *   decrypt function. Credential handling belongs exclusively to provider
 *   adapters and sync execution.
 */

import type { SpaceMemberRole } from '@prisma/client';

// ---------------------------------------------------------------------------
// Domain type
// ---------------------------------------------------------------------------

/**
 * An open string key identifying a context domain (e.g. "accounts",
 * "transactions_summary"). Not an enum — new templates add new strings
 * without modifying this file.
 */
export type ContextDomain = string;

/**
 * Built-in domain keys for the finance template.
 * Other templates (Travel, Business, Property, …) define their own
 * constants in their respective assembler directories.
 */
export const FinanceDomains = {
  ACCOUNTS:             'accounts',
  TRANSACTIONS_SUMMARY: 'transactions_summary',
  TRANSACTIONS_RAW:     'transactions_raw',
  HOLDINGS_SUMMARY:     'holdings_summary',
  HOLDINGS_RAW:         'holdings_raw',
  GOALS:                'goals',
  MEMBERS:              'members',
  SNAPSHOT_HISTORY:     'snapshot_history',
  PROVIDERS:            'providers',
  PLATFORM_HEALTH:      'platform_health',
} as const;

export type FinanceDomain = typeof FinanceDomains[keyof typeof FinanceDomains];

// ---------------------------------------------------------------------------
// Domain section
// ---------------------------------------------------------------------------

/**
 * The output of a single domain assembler. The `data` field is intentionally
 * `unknown` — consumers type-narrow against their own interfaces.
 */
export interface ContextDomainSection {
  domain:      string;
  assembledAt: string; // ISO-8601
  data:        unknown;
}

// ---------------------------------------------------------------------------
// Assembler options
// ---------------------------------------------------------------------------

/**
 * Options threaded through to each assembler invocation.
 * `scopeHint` lets callers signal intent without changing the domain list:
 *   - 'brief'  → assembler may return a condensed summary (for Daily Brief)
 *   - 'full'   → assembler returns the complete section (default)
 */
export interface AssemblerOptions {
  scopeHint?: 'full' | 'brief';
}

// ---------------------------------------------------------------------------
// Signals
// ---------------------------------------------------------------------------

/**
 * A deterministic, rule-based signal emitted by a signal detector after
 * context assembly. Signals are NOT generated by LLMs.
 *
 * Severity levels:
 *   - 'info'     → informational, no action required
 *   - 'warning'  → condition worth surfacing to the user
 *   - 'critical' → requires prompt attention
 */
export interface ContextSignal {
  id:        string;           // stable deterministic id, e.g. `${domain}:${ruleId}`
  domain:    string;           // which ContextDomain produced this signal
  spaceId:   string;
  severity:  'info' | 'warning' | 'critical';
  title:     string;
  body?:     string;
  value?:    number;           // observed value (e.g. balance)
  threshold?: number;          // rule threshold that triggered this signal
  metadata?: Record<string, unknown>;
  detectedAt: string;          // ISO-8601
}

// ---------------------------------------------------------------------------
// Domain-specific data shapes
// ---------------------------------------------------------------------------

/**
 * Health summary for the accounts domain.
 * Account names are only populated for FULL-visibility accounts — BALANCE_ONLY
 * accounts contribute to error/stale counts but their names are never exposed.
 */
export interface AccountHealthSummary {
  errorCount:              number;
  staleCount:              number;
  needsReauthCount:        number;
  errorAccountNames:       string[]; // FULL visibility only
  staleAccountNames:       string[]; // FULL visibility only
  needsReauthAccountNames: string[]; // FULL visibility only
}

/**
 * A single account entry in the accounts domain section.
 * `name` is always the display-safe name — real name for FULL, generic label
 * for BALANCE_ONLY. `institution` is omitted on BALANCE_ONLY entries.
 */
export interface AccountSummaryItem {
  id:               string;
  name:             string;
  type:             string;
  institution?:     string;
  balance:          number;
  currency:         string;
  lastUpdated:      string; // ISO-8601
  syncStatus?:      string | null;
  needsReauth:      boolean;
  visibilityLevel:  'FULL' | 'BALANCE_ONLY';
}

/**
 * Data payload for the 'accounts' context domain.
 *
 * All monetary values are in the Space's primary currency (USD unless the
 * majority of accounts differ). Mixed-currency balances are summed without
 * conversion — a known limitation until multi-currency support lands.
 *
 * When assembled with scopeHint='brief', the `accounts` array is omitted
 * to reduce payload size for the Daily Brief aggregator.
 */
export interface AccountsSectionData {
  totalCount:         number;
  totalAssets:        number;
  totalLiabilities:   number;
  netWorth:           number;
  totalLiquid:        number;
  totalInvestments:   number;
  totalDigitalAssets: number;
  totalRealAssets:    number;
  counts: {
    liquid:       number;
    investments:  number;
    digitalAssets: number;
    realAssets:   number;
    liabilities:  number;
  };
  health:    AccountHealthSummary;
  accounts?: AccountSummaryItem[]; // omitted when scopeHint === 'brief'
}

// ---------------------------------------------------------------------------
// Transactions summary domain types
// ---------------------------------------------------------------------------

/**
 * Spending/income total for a single transaction category.
 * `total` is always a positive number representing absolute value of spend
 * (for expense categories) or raw inflow (for income categories).
 */
export interface CategorySpend {
  category: string; // TransactionCategory value
  total:    number; // absolute value
  count:    number;
}

/**
 * A merchant that appears two or more times in the query window —
 * a deterministic, rule-based indicator of a recurring charge.
 * No ML or LLM required.
 */
export interface RecurringCandidate {
  merchant:      string;
  occurrences:   number;
  typicalAmount: number; // mean amount across occurrences (negative = expense)
  category:      string;
}

/**
 * Data payload for the 'transactions_summary' context domain.
 *
 * Summarizes banking transaction activity over a sliding window.
 * Raw transaction rows are never included — this domain is intentionally
 * aggregated-only to keep the context payload lean and avoid exposing
 * line-item detail to AI consumers by default.
 *
 * Amount sign convention (mirrors Plaid / existing codebase):
 *   positive → money in  (income, interest, incoming transfers)
 *   negative → money out (expenses, payments, outgoing transfers)
 *
 * `byCategory` lists all categories present in the window.
 * `recurringCandidates` is omitted when scopeHint='brief'.
 */
export interface TransactionsSummaryData {
  windowDays:       number;
  startDate:        string; // YYYY-MM-DD — window floor
  endDate:          string; // YYYY-MM-DD — most recent transaction date (or today)
  transactionCount: number; // settled + pending

  // ── Cash flow totals ────────────────────────────────────────────────────
  /** Sum of positive amounts in Income + Interest categories. */
  incomeTotal:       number;
  /** Absolute sum of negative amounts in non-transfer, non-payment categories. */
  expenseTotal:      number;
  /** Absolute sum of Payment category (debt repayment). */
  debtPaymentTotal:  number;
  /** Absolute sum of Transfer category (internal moves, both directions). */
  transferTotal:     number;
  /** incomeTotal − expenseTotal − debtPaymentTotal (excludes transfers). */
  netCashFlow:       number;

  // ── Pending ─────────────────────────────────────────────────────────────
  pendingCreditCount: number;
  pendingCreditTotal: number;
  pendingDebitCount:  number;
  /** Absolute value of pending outflows. */
  pendingDebitTotal:  number;

  // ── By category ─────────────────────────────────────────────────────────
  byCategory: CategorySpend[];

  // ── Highlights ──────────────────────────────────────────────────────────
  largestIncome:  { merchant: string; amount: number; date: string } | null;
  largestExpense: { merchant: string; amount: number; date: string } | null;

  // ── Recurring candidates (omitted on scopeHint='brief') ─────────────────
  recurringCandidates?: RecurringCandidate[];
}

// ---------------------------------------------------------------------------
// Snapshot domain types
// ---------------------------------------------------------------------------

/**
 * A single SpaceSnapshot data point, normalized for AI consumption.
 * Field names are semantically clear rather than terse DB column aliases.
 */
export interface SnapshotDataPoint {
  date:         string; // YYYY-MM-DD
  netWorth:     number;
  totalAssets:  number;
  liabilities:  number; // `debt` column — positive absolute value
  liquid:       number; // cash + savings
  investments:  number; // `stocks` column
  digitalAssets: number; // `crypto` column
  cashOnHand:   number;
  netLiquid:    number;
}

/**
 * Data payload for the 'snapshot_history' context domain.
 *
 * `history` is bounded (≤ SNAPSHOT_HISTORY_LIMIT rows, newest-last).
 * When assembled with scopeHint='brief', `history` is omitted and only
 * `latest` + trend deltas are returned.
 */
export interface SnapshotSectionData {
  snapshotCount:   number;
  oldestDate:      string | null; // YYYY-MM-DD
  newestDate:      string | null; // YYYY-MM-DD
  /** Absolute net-worth change from oldest to newest in the window. */
  netWorthTrend:   number | null; // null if fewer than 2 snapshots
  /** Percentage change, null if oldest net worth was 0. */
  netWorthTrendPct: number | null;
  latest:          SnapshotDataPoint | null;
  history:         SnapshotDataPoint[]; // omitted on scopeHint='brief'
}

// ---------------------------------------------------------------------------
// Goals domain types
// ---------------------------------------------------------------------------

/**
 * A single goal summary for AI context.
 * Only fields relevant to AI-generated advice are included.
 * Sensitive or purely-UI fields (description, spendingCategory, etc.) are
 * omitted to keep the context payload lean.
 */
export interface GoalSummaryItem {
  id:       string;
  name:     string;
  category: string; // GoalCategory
  goalType: string; // GoalType
  status:   string; // GoalStatus

  // FINANCIAL / SPENDING_LIMIT — amounts and progress
  targetAmount?:  number | null;
  currentAmount?: number;
  /** 0-100 integer, null when not computable (HABIT, DEBT_REDUCTION). */
  progressPct?:   number | null;
  targetDate?:    string | null; // YYYY-MM-DD

  // DEBT_REDUCTION — debt-specific reduction targets
  targetReductionAmount?: number | null;
  targetReductionPct?:    number | null;
  snapshotBalance?:       number | null;

  // HABIT — streak tracking
  habitFrequency?: string | null;
  currentStreak?:  number;
  longestStreak?:  number;
  lastCheckIn?:    string | null; // ISO-8601

  completedAt?: string | null; // ISO-8601
}

/**
 * Data payload for the 'goals' context domain.
 */
export interface GoalsSectionData {
  totalCount: number;
  counts: {
    active:    number;
    paused:    number;
    completed: number;
  };
  goals: GoalSummaryItem[];
}

// ---------------------------------------------------------------------------
// Assembled context
// ---------------------------------------------------------------------------

/**
 * The complete AI context object returned by buildContext().
 *
 * `domains` is an open map keyed by ContextDomain string — consumers
 * access sections by key (e.g. ctx.domains['accounts']) rather than
 * by named interface fields. This supports templates that declare
 * entirely different domain sets.
 *
 * `signals` is the flat list of all signals detected across all assembled
 * domains, sorted by severity then detectedAt.
 *
 * `auditLogId` is the ID of the AuditLog row created on assembly.
 * Consumers may reference it for traceability.
 */
export interface SpaceContext_AI {
  requestedAt:     string; // ISO-8601
  spaceId:         string;
  userId:          string;
  role:            SpaceMemberRole;
  agentId:         string;
  resolvedDomains: string[]; // ordered list of domains that were attempted
  space: {
    id:       string;
    name:     string;
    type:     string;
    category: string;
  };
  domains:     Record<string, ContextDomainSection>;
  signals:     ContextSignal[];
  auditLogId:  string;
}
