/**
 * lib/ai/types.ts
 *
 * Core type contracts for the AI Context Builder (D4).
 *
 * Design principles:
 * - ContextDomain is an open string type, not an enum. This keeps the
 *   contract template-agnostic — finance, travel, business, property, and
 *   future Space types all register their own domain strings without touching
 *   this file.
 * - FinanceDomains provides the canonical constants for the built-in finance
 *   template. Non-finance templates define their own constants elsewhere.
 * - SpaceContext_AI uses an open Record<string, ContextDomainSection> for
 *   domains rather than named fields, for the same reason.
 * - Signals are deterministic and rule-based. No LLM calls here.
 *
 * Security invariant (enforced by lint rule — see eslint config):
 *   No file under lib/ai/ may import lib/plaid/encryption or call any
 *   decrypt function. Credential handling belongs exclusively to provider
 *   adapters and sync execution.
 */

import type { SpaceMemberRole } from '@prisma/client';

// ---------------------------------------------------------------------------
// Domain type
// ---------------------------------------------------------------------------

/**
 * An open string key identifying a context domain (e.g. "accounts",
 * "transactions_summary"). Not an enum — new templates add new strings
 * without modifying this file.
 */
export type ContextDomain = string;

/**
 * Built-in domain keys for the finance template.
 * Other templates (Travel, Business, Property, …) define their own
 * constants in their respective assembler directories.
 */
export const FinanceDomains = {
  ACCOUNTS:             'accounts',
  TRANSACTIONS_SUMMARY: 'transactions_summary',
  TRANSACTIONS_RAW:     'transactions_raw',
  HOLDINGS_SUMMARY:     'holdings_summary',
  HOLDINGS_RAW:         'holdings_raw',
  GOALS:                'goals',
  MEMBERS:              'members',
  SNAPSHOT_HISTORY:     'snapshot_history',
  PROVIDERS:            'providers',
  PLATFORM_HEALTH:      'platform_health',
} as const;

export type FinanceDomain = typeof FinanceDomains[keyof typeof FinanceDomains];

// ---------------------------------------------------------------------------
// Domain section
// ---------------------------------------------------------------------------

/**
 * The output of a single domain assembler. The `data` field is intentionally
 * `unknown` — consumers type-narrow against their own interfaces.
 */
export interface ContextDomainSection {
  domain:      string;
  assembledAt: string; // ISO-8601
  data:        unknown;
}

// ---------------------------------------------------------------------------
// Assembler options
// ---------------------------------------------------------------------------

/**
 * Options threaded through to each assembler invocation.
 * `scopeHint` lets callers signal intent without changing the domain list:
 *   - 'brief'  → assembler may return a condensed summary (for Daily Brief)
 *   - 'full'   → assembler returns the complete section (default)
 */
export interface AssemblerOptions {
  scopeHint?: 'full' | 'brief';
}

// ---------------------------------------------------------------------------
// Signals
// ---------------------------------------------------------------------------

/**
 * A deterministic, rule-based signal emitted by a signal detector after
 * context assembly. Signals are NOT generated by LLMs.
 *
 * Severity levels:
 *   - 'info'     → informational, no action required
 *   - 'warning'  → condition worth surfacing to the user
 *   - 'critical' → requires prompt attention
 */
export interface ContextSignal {
  id:        string;           // stable deterministic id, e.g. `${domain}:${ruleId}`
  domain:    string;           // which ContextDomain produced this signal
  spaceId:   string;
  severity:  'info' | 'warning' | 'critical';
  title:     string;
  body?:     string;
  value?:    number;           // observed value (e.g. balance)
  threshold?: number;          // rule threshold that triggered this signal
  metadata?: Record<string, unknown>;
  detectedAt: string;          // ISO-8601
}

// ---------------------------------------------------------------------------
// Assembled context
// ---------------------------------------------------------------------------

/**
 * The complete AI context object returned by buildContext().
 *
 * `domains` is an open map keyed by ContextDomain string — consumers
 * access sections by key (e.g. ctx.domains['accounts']) rather than
 * by named interface fields. This supports templates that declare
 * entirely different domain sets.
 *
 * `signals` is the flat list of all signals detected across all assembled
 * domains, sorted by severity then detectedAt.
 *
 * `auditLogId` is the ID of the AuditLog row created on assembly.
 * Consumers may reference it for traceability.
 */
export interface SpaceContext_AI {
  requestedAt:     string; // ISO-8601
  spaceId:         string;
  userId:          string;
  role:            SpaceMemberRole;
  agentId:         string;
  resolvedDomains: string[]; // ordered list of domains that were attempted
  space: {
    id:       string;
    name:     string;
    type:     string;
    category: string;
  };
  domains:     Record<string, ContextDomainSection>;
  signals:     ContextSignal[];
  auditLogId:  string;
}
